export default {
  // orientation
  ORIENTATION_PORTRAIT: 1,
  ORIENTATION_LANDSCAPE: 2,
  ORIENTATION_AUTO: 3,

  // browser type
  BROWSER_TYPE_WECHAT: 'wechat',
  BROWSER_TYPE_WECHAT_GAME: 'wechatgame',
  BROWSER_TYPE_WECHAT_GAME_SUB: 'wechatgamesub',
  BROWSER_TYPE_QQ_PLAY: 'qqplay',
  BROWSER_TYPE_ANDROID: 'androidbrowser',
  BROWSER_TYPE_IE: 'ie',
  BROWSER_TYPE_QQ: 'qqbrowser',
  BROWSER_TYPE_MOBILE_QQ: 'mqqbrowser',
  BROWSER_TYPE_UC: 'ucbrowser',
  BROWSER_TYPE_UCBS: 'ucbs',
  BROWSER_TYPE_360: '360browser',
  BROWSER_TYPE_BAIDU_APP: 'baiduboxapp',
  BROWSER_TYPE_BAIDU: 'baidubrowser',
  BROWSER_TYPE_MAXTHON: 'maxthon',
  BROWSER_TYPE_OPERA: 'opera',
  BROWSER_TYPE_OUPENG: 'oupeng',
  BROWSER_TYPE_MIUI: 'miuibrowser',
  BROWSER_TYPE_FIREFOX: 'firefox',
  BROWSER_TYPE_SAFARI: 'safari',
  BROWSER_TYPE_CHROME: 'chrome',
  BROWSER_TYPE_LIEBAO: 'liebao',
  BROWSER_TYPE_QZONE: 'qzone',
  BROWSER_TYPE_SOUGOU: 'sogou',
  BROWSER_TYPE_UNKNOWN: 'unknown',
  // os
  OS_UNKNOWN: 'Unknown',
  OS_IOS: 'iOS',
  OS_ANDROID: 'Android',
  OS_WINDOWS: 'Windows',
  OS_MARMALADE: 'Marmalade',
  OS_LINUX: 'Linux',
  OS_BADA: 'Bada',
  OS_BLACKBERRY: 'Blackberry',
  OS_OSX: 'OS X',
  OS_WP8: 'WP8',
  OS_WINRT: 'WINRT',
};
